import type { Destination, GeneratedDay, TravelStyle } from "@/types/travixa";

export const travelStyles: TravelStyle[] = [
  {
    name: "Adventure",
    description: "Rafting, treks, high passes, zip lines, and plans with momentum.",
    icon: "A",
    accent: "from-emerald-400 to-cyan-500",
  },
  {
    name: "Luxury",
    description: "Design-led stays, private transfers, slow mornings, and polished dining.",
    icon: "L",
    accent: "from-amber-300 to-rose-400",
  },
  {
    name: "Solo Travel",
    description: "Safe, flexible routes with social stays and easy local movement.",
    icon: "S",
    accent: "from-sky-400 to-indigo-500",
  },
  {
    name: "Couple Escape",
    description: "Sunsets, boutique stays, quiet tables, and moments that breathe.",
    icon: "C",
    accent: "from-rose-300 to-fuchsia-500",
  },
  {
    name: "Hidden Gems",
    description: "Lesser-known neighborhoods, trails, cafes, craft clusters, and viewpoints.",
    icon: "H",
    accent: "from-lime-300 to-teal-500",
  },
  {
    name: "Food Explorer",
    description: "Street food, regional kitchens, market walks, and chef-led recommendations.",
    icon: "F",
    accent: "from-orange-300 to-red-500",
  },
  {
    name: "Photography",
    description: "Golden-hour routes, textured lanes, landscapes, and cinematic frames.",
    icon: "P",
    accent: "from-violet-300 to-blue-500",
  },
  {
    name: "Weekend Trips",
    description: "Short, efficient escapes built around Friday departures and Monday energy.",
    icon: "W",
    accent: "from-cyan-300 to-emerald-500",
  },
];

export const destinations: Destination[] = [
  {
    name: "Goa",
    slug: "goa",
    state: "Goa",
    description: "A coastal escape for beaches, Portuguese quarters, seafood, late sunsets, and relaxed drives.",
    coverImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    bestTimeToVisit: "November to February",
    budgetRange: "Rs. 12,000 - Rs. 45,000",
    highlights: ["Beaches", "Night markets", "Seafood", "Heritage walks"],
    hiddenGems: ["Divar Island", "Chorla Ghats", "Fontainhas mornings"],
    attractions: ["Baga Beach", "Fort Aguada", "Basilica of Bom Jesus"],
    localExperiences: ["Latin Quarter walk", "Spice plantation lunch", "Sunset kayak"],
    foodRecommendations: ["Goan fish thali", "Poi bread", "Bebinca", "Ros omelette"],
  },
  {
    name: "Jaipur",
    slug: "jaipur",
    state: "Rajasthan",
    description: "A vivid heritage city with forts, craft bazaars, pink facades, palace stays, and bold food.",
    coverImage: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
    bestTimeToVisit: "October to March",
    budgetRange: "Rs. 9,500 - Rs. 38,000",
    highlights: ["Forts", "Markets", "Craft", "Rajasthani food"],
    hiddenGems: ["Panna Meena ka Kund", "Galta Ji", "Anokhi Museum"],
    attractions: ["Amber Fort", "Hawa Mahal", "City Palace"],
    localExperiences: ["Block-printing workshop", "Bazaar trail", "Rooftop dinner"],
    foodRecommendations: ["Pyaaz kachori", "Laal maas", "Ghewar", "Kulhad lassi"],
  },
  {
    name: "Udaipur",
    slug: "udaipur",
    state: "Rajasthan",
    description: "A romantic lake city of palaces, rooftop restaurants, boat rides, and soft golden evenings.",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/City%20Palace%20on%20Lake%20Pichola%20%2851728937130%29.jpg?width=1200",
    bestTimeToVisit: "October to March",
    budgetRange: "Rs. 10,000 - Rs. 55,000",
    highlights: ["Lakes", "Palaces", "Rooftops", "Art lanes"],
    hiddenGems: ["Badi Lake", "Shilpgram", "Ambrai sunrise"],
    attractions: ["City Palace", "Lake Pichola", "Sajjangarh Palace"],
    localExperiences: ["Miniature painting studio", "Boat ride", "Old city walk"],
    foodRecommendations: ["Dal baati churma", "Mewari thali", "Kachori", "Rabri"],
  },
  {
    name: "Rishikesh",
    slug: "rishikesh",
    state: "Uttarakhand",
    description: "A Ganga-side base for rafting, yoga, cafes, forest walks, and wellness-focused travel.",
    coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    bestTimeToVisit: "September to June",
    budgetRange: "Rs. 9,000 - Rs. 32,000",
    highlights: ["Rafting", "Yoga", "Cafes", "Ganga aarti"],
    hiddenGems: ["Neer Garh waterfall", "Kunjapuri sunrise", "Beatles Ashram corners"],
    attractions: ["Lakshman Jhula", "Triveni Ghat", "Beatles Ashram"],
    localExperiences: ["Morning yoga", "White-water rafting", "Aarti by the river"],
    foodRecommendations: ["Aloo puri", "Cafe bowls", "Jalebi", "Garhwali thali"],
  },
  {
    name: "Manali",
    slug: "manali",
    state: "Himachal Pradesh",
    description: "A mountain classic for snow, valleys, cafes, paragliding, road trips, and alpine views.",
    coverImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80",
    bestTimeToVisit: "October to June",
    budgetRange: "Rs. 15,000 - Rs. 50,000",
    highlights: ["Snow", "Cafes", "Valleys", "Adventure"],
    hiddenGems: ["Sethan", "Jana waterfall", "Hamta village"],
    attractions: ["Solang Valley", "Hadimba Temple", "Old Manali"],
    localExperiences: ["Cafe hopping", "Paragliding", "Apple orchard walk"],
    foodRecommendations: ["Trout", "Siddu", "Thukpa", "Himachali dham"],
  },
  {
    name: "Leh",
    slug: "leh",
    state: "Ladakh",
    description: "A high-altitude route through monasteries, stark landscapes, blue lakes, and dramatic passes.",
    coverImage: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80",
    bestTimeToVisit: "May to September",
    budgetRange: "Rs. 25,000 - Rs. 75,000",
    highlights: ["Monasteries", "Pangong", "Passes", "Stargazing"],
    hiddenGems: ["Basgo ruins", "Sumur village", "Turtuk lanes"],
    attractions: ["Pangong Lake", "Thiksey Monastery", "Khardung La"],
    localExperiences: ["Monastery breakfast", "Homestay dinner", "Night-sky session"],
    foodRecommendations: ["Momos", "Skyu", "Butter tea", "Apricot jam"],
  },
  {
    name: "Kerala",
    slug: "kerala",
    state: "Kerala",
    description: "A lush route through backwaters, tea gardens, beaches, wildlife, Ayurveda, and houseboat stays.",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Alleppey%20Backwaters.jpg?width=1200",
    bestTimeToVisit: "September to March",
    budgetRange: "Rs. 18,000 - Rs. 60,000",
    highlights: ["Backwaters", "Tea gardens", "Houseboats", "Ayurveda"],
    hiddenGems: ["Munroe Island", "Marari Beach", "Vagamon meadows"],
    attractions: ["Alleppey Backwaters", "Munnar", "Fort Kochi"],
    localExperiences: ["Houseboat cruise", "Spice garden walk", "Kathakali evening"],
    foodRecommendations: ["Appam stew", "Kerala sadya", "Karimeen pollichathu", "Banana chips"],
  },
  {
    name: "Kashmir",
    slug: "kashmir",
    state: "Jammu and Kashmir",
    description: "A scenic valley escape with lakes, gardens, meadows, snow activities, and mountain views.",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Kashmir%20Dal%20lake.jpg?width=1200",
    bestTimeToVisit: "March to October and December to February",
    budgetRange: "Rs. 22,000 - Rs. 70,000",
    highlights: ["Dal Lake", "Meadows", "Snow", "Houseboats"],
    hiddenGems: ["Doodhpathri", "Aharbal waterfall", "Nigeen Lake"],
    attractions: ["Srinagar", "Gulmarg", "Pahalgam"],
    localExperiences: ["Shikara ride", "Kahwa tasting", "Meadow picnic"],
    foodRecommendations: ["Rogan josh", "Kahwa", "Gushtaba", "Modur pulao"],
  },
  {
    name: "Andaman",
    slug: "andaman",
    state: "Andaman and Nicobar Islands",
    description: "An island escape for turquoise beaches, scuba diving, snorkeling, ferries, and quiet coastal stays.",
    coverImage: "https://commons.wikimedia.org/wiki/Special:FilePath/Radhanagar%20Beach%20on%20Havelock%20Island%20of%20Andaman%20and%20Nicobar%20Archipelago..jpg?width=1200",
    bestTimeToVisit: "October to May",
    budgetRange: "Rs. 28,000 - Rs. 85,000",
    highlights: ["Beaches", "Scuba", "Snorkeling", "Island ferries"],
    hiddenGems: ["Kalapathar Beach", "Chidiya Tapu", "Neil Island coves"],
    attractions: ["Radhanagar Beach", "Cellular Jail", "Havelock Island"],
    localExperiences: ["Scuba dive", "Sunset beach walk", "Island hopping"],
    foodRecommendations: ["Grilled seafood", "Coconut curry", "Fish thali", "Tropical fruit bowls"],
  },
];

export const generatedItinerary: GeneratedDay[] = [
  {
    day: "Day 1",
    title: "Arrival and orientation",
    plan: "Check in, settle into the neighborhood, take a low-effort local walk, and end with a regional dinner.",
  },
  {
    day: "Day 2",
    title: "Signature experiences",
    plan: "Cover the must-see attraction early, add one guided local experience, and keep sunset open for a viewpoint.",
  },
  {
    day: "Day 3",
    title: "Hidden gems and slow exit",
    plan: "Visit a quieter spot, shop or cafe-hop locally, then leave buffer time for transfers and final photos.",
  },
];
